# Generated by Django 2.1.2 on 2019-04-22 05:25

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='用于URL地址，请勿填写中文', unique=True, verbose_name='活动标题')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='activity', verbose_name='活动图片')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '活动名',
                'verbose_name_plural': '活动名',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='自我简介')),
                ('avatar', imagekit.models.fields.ProcessedImageField(upload_to='basketball_avatar', verbose_name='头像')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='票数')),
            ],
            options={
                'verbose_name': '参赛选手',
                'verbose_name_plural': '参赛选手',
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basketball.Candidate', verbose_name='选择的投票对象')),
            ],
            options={
                'verbose_name': '投票记录',
                'verbose_name_plural': '投票记录',
            },
        ),
    ]
