# Generated by Django 2.1.2 on 2018-11-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': '参赛选手'},
        ),
    ]
