# Generated by Django 2.1.2 on 2019-04-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball', '0003_auto_20181108_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='activity',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='自我简介'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, verbose_name='手机号'),
        ),
    ]
