# Generated by Django 2.1.2 on 2019-04-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreyListDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_time', models.CharField(max_length=40, verbose_name='证据时间')),
                ('risk_level', models.CharField(max_length=20, verbose_name='风险登记')),
                ('fraud_type', models.CharField(max_length=30, verbose_name='诈骗类型')),
                ('fraud_type_display_name', models.CharField(max_length=30, verbose_name='诈骗类型显示名')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_display_name', models.CharField(max_length=30, verbose_name='行业显示名')),
                ('count', models.CharField(max_length=20, verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='RiskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_type_display_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='命中类型显示名')),
                ('fraud_type_display_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='诈骗类型显示名')),
                ('description', models.CharField(max_length=50, verbose_name='描述')),
                ('type', models.CharField(max_length=30, verbose_name='类型')),
                ('platform_count', models.CharField(blank=True, max_length=20, null=True, verbose_name='平台借贷数量')),
            ],
        ),
        migrations.CreateModel(
            name='RiskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=20, verbose_name='分数')),
                ('risk_name', models.CharField(max_length=40, verbose_name='风险名')),
                ('decision', models.CharField(max_length=20, verbose_name='决策结果')),
            ],
        ),
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('id_number', models.CharField(max_length=30, unique=True, verbose_name='身份证号')),
                ('credit_score', models.CharField(max_length=20, verbose_name='同盾信用分')),
                ('final_score', models.CharField(max_length=20, verbose_name='租赁分')),
                ('final_decision', models.CharField(max_length=20, verbose_name='同盾决策结果')),
            ],
        ),
        migrations.AddField(
            model_name='riskitem',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmodel.UserBase', verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='riskdetail',
            name='risk_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmodel.RiskItem', verbose_name='risk_item_id'),
        ),
        migrations.AddField(
            model_name='platformdetail',
            name='risk_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmodel.RiskDetail', verbose_name='risk_detail_id'),
        ),
        migrations.AddField(
            model_name='greylistdetail',
            name='risk_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmodel.RiskDetail', verbose_name='risk_detail_id'),
        ),
    ]
