# Generated by Django 2.1.2 on 2019-04-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmodel', '0002_auto_20190420_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=80, verbose_name='细节内容')),
                ('type', models.CharField(max_length=80, verbose_name='类型')),
                ('risk_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmodel.RiskDetail', verbose_name='risk_detail_id')),
            ],
        ),
    ]
