# Generated by Django 2.1.2 on 2018-10-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商户名')),
                ('address', models.CharField(max_length=200, verbose_name='商户地址')),
                ('boss_name', models.CharField(max_length=20, verbose_name='老板姓名')),
                ('mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('bank_number', models.CharField(max_length=30, verbose_name='银行卡号')),
                ('commission_rate', models.FloatField(blank=True, null=True, verbose_name='佣金比例')),
                ('business_license', models.ImageField(blank=True, default='', null=True, upload_to='business_license', verbose_name='营业执照')),
                ('id_card_no', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='身份证号码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('qrcode', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='二维码')),
            ],
        ),
    ]
