# Generated by Django 2.1.2 on 2018-10-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='商户名')),
                ('address', models.CharField(max_length=300, verbose_name='商户地址')),
                ('boss_name', models.CharField(max_length=20, verbose_name='老板姓名')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('bank_number', models.CharField(max_length=30, verbose_name='银行卡号')),
                ('commission_rate', models.IntegerField()),
                ('business_license', models.ImageField(upload_to='business_license', verbose_name='营业执照')),
                ('ID_number', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
