# Generated by Django 2.1.2 on 2018-10-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181013_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='ID_number',
            field=models.CharField(max_length=30, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
    ]
