# Generated by Django 2.1.2 on 2018-10-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181013_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='ID_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_license',
            field=models.ImageField(blank=True, upload_to='business_license', verbose_name='营业执照'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='commission_rate',
            field=models.FloatField(blank=True, verbose_name='佣金比例'),
        ),
    ]
