# Generated by Django 2.1.2 on 2018-10-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181015_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='qrcode',
            field=models.CharField(blank=True, max_length=200, verbose_name='二维码'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='address',
            field=models.CharField(max_length=200, verbose_name='商户地址'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(max_length=20, verbose_name='商户名'),
        ),
    ]
