# Generated by Django 2.1.2 on 2018-10-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181016_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='commission_rate',
            field=models.CharField(blank=True, max_length=20, verbose_name='佣金比例'),
        ),
    ]
