# Generated by Django 2.1.2 on 2018-10-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181016_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='ID_number',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='business_license',
            field=models.ImageField(blank=True, default='', null=True, upload_to='business_license', verbose_name='营业执照'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='qrcode',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='二维码'),
        ),
    ]
