# Generated by Django 2.1.2 on 2018-10-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181016_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='ID_number',
            new_name='id_card_no',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='modified_time',
            new_name='update_time',
        ),
    ]
